entrada = input('INFORME A ENTRADA ')
print(f'O TIPO PRIMITIVO DESSE VALOR É: {type(entrada)}')
print(f'TEM ESPAÇOS? {entrada.isspace}')
print(f'É UM NUMERO? {entrada.isnumeric}')
print(f'É ALFABÉTICO? {entrada.isalfa}')
print(f'É ALFANUMÉRICO {entrada.isalnum}')
print(f'ESTA EM LETRAS MAIÚSCULAS? {entrada.tupper}')
print(f'ESTA EM LETRAS MINÚSCULAS? {entrada.lower}')
print(f'ESTA CAPITALIZADA? {entrada.istitle}')
